#!/usr/bin/env bash

# no .in files, they get broken (and also aren't always source files)
CXX_CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -Ee "\.([chi](pp)|[chi]|cu)$")

# if not working, run $ sudo apt install clang-format-x
/usr/bin/clang-format -i -style=file ${CXX_CHANGED_FILES}
git add ${CXX_CHANGED_FILES}
