name: build

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        preset: [gcc-debug, gcc-release, clang-debug, clang-release]

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'false'

    - name: Initialize submodules
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule update --init --recursive --recommend-shallow

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.3'
        target: 'desktop'
        install-deps: 'true'
        modules: 'qt5compat'
        cache: 'false'
        setup-python: 'false'
        set-env: 'true'

    - name: Configure CMake
      run: cmake --preset ${{matrix.preset}}

    - name: Build
      run: cmake --build --preset ${{matrix.preset}}

    - name: Test
      run: ctest --preset ${{matrix.preset}}
