name: build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            preset: gcc-debug
          - os: ubuntu-24.04
            preset: gcc-release
          - os: ubuntu-24.04
            preset: clang-debug
          - os: ubuntu-24.04
            preset: clang-release
          - os: windows-2022
            preset: msvc-debug
          - os: windows-2022
            preset: msvc-release

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'false'

    - name: Initialize submodules
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule update --init --recursive --recommend-shallow

    - name: Set up MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Qt
      if: runner.os != 'Windows'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.3'
        target: 'desktop'
        install-deps: 'true'
        modules: 'qt5compat'
        cache: 'false'
        setup-python: 'false'
        set-env: 'true'

    - name: Install Qt
      if: runner.os == 'Windows'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        install-deps: 'true'
        modules: 'qt5compat'
        cache: 'false'
        setup-python: 'false'
        set-env: 'true'

    - name: Configure CMake
      run: cmake --preset ${{matrix.preset}}

    - name: Build
      run: cmake --build --preset ${{matrix.preset}}

    - name: Test
      run: ctest --preset ${{matrix.preset}}

  dependabot-automerge:
    needs:
      - build
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      !github.event.pull_request.draft
    uses: devmarkusb/devenv/.github/workflows/dependabot-automerge.yml@main
